name = "traintracker"
compatibility_date = "2024-03-20"

[site]
bucket = "./"

[[kv_namespaces]]
binding = "TRAIN_TRACKER_KV"
id = "6f83b88f37334f8e9dbcfe8d2c1f8672"
preview_id = "train-tracker-kv-preview" 